# Generated by Django 6.0.2 on 2026-10-09 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("learning_logs", "0004_topic_public"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="entry",
            name="date_added",
        ),
        migrations.RemoveField(
            model_name="topic",
            name="date_added",
        ),
    ]
